SICPy: Chapter 1.0-1.1
source-academy/sicpy pull request #1
Opened 2023-05-08 14:40 UTC by Fidget-Spinner

Some stuff up for discussion.

2023-05-11 15:52 UTC, Fidget-Spinner commented on xml/chapter1/chapter1.xml
> +  After van Rossum's initial implementation at CWI, Python has been updated
```suggestion
  After Van Rossum's initial implementation at CWI, Python has been updated
```

2023-05-20 09:24 UTC, Fidget-Spinner commented on xml/chapter1/chapter1.xml
> +        operating system.
I should reference Guido's blog.

2023-05-23 05:32 UTC, martin-henz requested changes

2023-05-23 05:32 UTC, martin-henz commented on xml/chapter1/section1/subsection1.xml
> +	statement.<FOOTNOTE>Expression statements in Python produce values in
Good call to get rid of the Oscar Wilde reference in this footnote.

2023-05-23 16:40 UTC, Fidget-Spinner commented
For some reason, there's mixed tabs and spaces in the document. I've tried to keep consistent with the rest of the surrounding text whenever that happens.

2023-05-24 08:35 UTC, martin-henz requested changes

2023-05-24 08:35 UTC, martin-henz commented on xml/chapter1/chapter1.xml
> +        The name <QUOTE>Python</QUOTE> is a reference to <EM>Monty Python</EM>
I think you can't expect "Monty Python" to be known across generations. It's already a bit "vintage". So I suggest:

..is a reference to the British comedy troupe < EM >Monty Python< /EM >...

2023-05-24 11:26 UTC, Fidget-Spinner commented on xml/chapter1/chapter1.xml
> +        <INDEX>Python interpreter, interpreting JavaScript</INDEX>
```suggestion
        <INDEX>Python interpreter, interpreting Python</INDEX>
```

2023-05-30 11:40 UTC, Fidget-Spinner commented
@martin-henz would it be alright if I merge the PR?

2023-05-31 03:03 UTC, martin-henz approved these changes

2023-05-31 03:10 UTC, merged